"""Generate native/src/AgentDesk.Contracts/Tools.g.cs (run: python native/tools/gen_tools.py) from agentdesk/mcp_server.py.

One file gives both sides what they need, with no reflection (so both can be Native AOT):
  Tools.All       name, description, JSON input schema per tool (the MCP shim lists these)
  Tools.Dispatch  tool name + JSON args -> IAgentBoard call, with the Python defaults (the core)
  Tools.Instructions  the server instructions agents see
"""
import ast, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]  # the AgentDesk repo
SRC = ROOT / "agentdesk" / "mcp_server.py"
OUT = ROOT / "native" / "src" / "AgentDesk.Contracts" / "Tools.g.cs"
NO_CALLER = {"formatting_help", "list_threads", "search_messages", "search_vault", "recent_messages", "list_work"}
CONSTS = {"db.CLAIM_AUTO": "auto"}
TYPES = {"str": ("string", "String", "string"), "int": ("int", "Int", "integer"), "bool": ("bool", "Bool", "boolean"),
         "dict": ("Dictionary<string, object?>", "Dict", "object")}

tree = ast.parse(SRC.read_text(encoding="utf-8"))
instructions = next(ast.literal_eval(kw.value) for n in tree.body if isinstance(n, ast.Assign)
                    and getattr(n.targets[0], "id", "") == "server" for kw in n.value.keywords if kw.arg == "instructions")


def cs_str(s):
    return '"""\n' + s + '\n"""' if ('"' in s or "\n" in s) else json.dumps(s)


tables, cases = [], []
for node in tree.body:
    if not (isinstance(node, ast.FunctionDef) and any(ast.unparse(d).startswith("server.tool") for d in node.decorator_list)):
        continue
    args = node.args.args
    defaults = [None] * (len(args) - len(node.args.defaults)) + node.args.defaults
    props, required, call = {}, [], ([] if node.name in NO_CALLER else ["c"])
    for a, d in zip(args, defaults):
        ann = ast.unparse(a.annotation).replace(" ", "")
        optional = ann.endswith("|None")
        cs, getter, js = TYPES[ann.removesuffix("|None")]
        props[a.arg] = {"type": js}
        if d is None:
            required.append(a.arg)
            call.append(f'a.{getter}("{a.arg}")')
        else:
            src = ast.unparse(d)
            val = CONSTS.get(src, None) if src in CONSTS else ast.literal_eval(d)
            if val is not None:
                props[a.arg]["default"] = val
            fallback = "null" if val is None else json.dumps(val) if not isinstance(val, bool) else str(val).lower()
            call.append(f'a.{getter}{"OrNull" if optional else ""}("{a.arg}"{"" if optional else ", " + fallback})')
    schema = json.dumps({"type": "object", "properties": props, "required": required})
    pascal = "".join(w.capitalize() for w in node.name.split("_"))
    tables.append(f'        new("{node.name}", {cs_str(ast.get_docstring(node) or "")}, {cs_str(schema)}),')
    cases.append(f'            "{node.name}" => b.{pascal}({", ".join(call)}),')

OUT.write_text(f"""// <auto-generated> by gen_tools.py from agentdesk/mcp_server.py. Regenerate, don't edit. </auto-generated>
#nullable enable
namespace AgentDesk.Contracts;

public static partial class Tools
{{
    public const string Instructions = {cs_str(instructions)};

    public static readonly ToolInfo[] All =
    [
{chr(10).join(tables)}
    ];

    static Task<string> Call(IAgentBoard b, Caller c, string tool, Args a) => tool switch
    {{
{chr(10).join(cases)}
            _ => Task.FromResult(Error($"no such tool: {{tool}}")),
    }};
}}
""", encoding="utf-8")
print("tools:", len(cases))
